### ISSUE TITLE
Missing pip

### ISSUE THREAD

**Issue by topiaruss** [hxpro/ansible-role-docker-engine#1]
TASK [hxpro.docker-engine : Install docker-compose] ****************************
failed: [default] (item=pip) => {"failed": true, "item": "pip", "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
failed: [default] (item=docker-compose) => {"failed": true, "item": "docker-compose", "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
failed: [default] (item=docker-py) => {"failed": true, "item": "docker-py", "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
	to retry, use: --limit @/Users/russ/tmp/centos/playbook.retry

**Comment by hxpro** [comment]
Thanks for your feedback. Try to install python-pip package.

**Comment by hxpro** [comment]
I just had added package pyhton-pip to the hxpro.bootstrap role.
